deploy:
  name: Deploy to GCE via SSH
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}

    - name: Package Application
      run: tar -czvf build.tar.gz -C build .

    - name: Deploy to Google Compute Engine
      uses: appleboy/scp-action@master
      with: 
        username: ${{ secrets.GCE_USER }}
        host: ${{ secrets.GCE_HOST }}
        key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
        source: "build.tar.gz"
        target: "/home/ubuntu/buildfiles"

    - name: Unzip and Move Static Files
      env:
        GCE_USER: ${{ secrets.GCE_USER }}
        GCE_HOST: ${{ secrets.GCE_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no $GCE_USER@$GCE_HOST "
          sudo tar -xzvf /home/ubuntu/buildfiles/build.tar.gz -C /home/ubuntu/static && 
          sudo rm /home/ubuntu/buildfiles/build.tar.gz
        "
